### ISSUE TITLE
Can you add a README.md file for this project?

### ISSUE THREAD

**Issue by jiangxincode** [JeremySkinner/posh-svn#10]
I have used the posh-git for a long time, but recently, for some reasons, I have to use the svn, so I find this project. I find you don't update this project for a long time. So i am wondering if you are still on it? And can you add a README.md for your project, from which we can get the installation/usage info?

**Comment by JeremySkinner** [comment]
Hi, this isn't an active project anymore I'm afraid - I don't use it and am not planning on changing/updating it. Sorry.

**Comment by jiangxincode** [comment]
Well, glad to receive your reply, but i want to know the reason that you give up it, It's a hopeless project or you meet some problems in the development or you don't have anytime to maintain it? And i want to keep it going on, and want your permission. This project follows what license? MIT, GPL or LGPL?
waiting your reply.

**Comment by JeremySkinner** [comment]
I don't use svn anymore, and haven't done so for many years, so it's not
worth it for me to continue support/maintenance.

You'd be more than welcome to take the code and continue to maintain it if
you like. It's based on the original code we wrote for posh-git, so would
come under the same license:
https://github.com/dahlbyk/posh-git/blob/master/LICENSE.txt
