### ISSUE TITLE
Pull request acceptance

### ISSUE THREAD

**Issue by ghost** [JeremySkinner/posh-svn#14]
Hello, can we get some of the pull requests accepted and the version updated on PsGet? Lots of helpful additions and changes. Thanks!

**Comment by JeremySkinner** [comment]
Hi, I don't actually develop or maintain posh-svn anymore I'm afraid. If you or someone else would like to fork the project and take it on, then you're more than welcome, but I personally won't be making any further updated, sorry.

**Comment by mbishopim3** [comment]
Understood. We took all of the pending pull requests and merged them (more or less) here: https://github.com/imobile3/posh-svn

If you and I can message and we can get access to PsGet, we'll maintain this library going forward.

**Comment by JeremySkinner** [comment]
That's great news...thanks for taking it on.

I didn't actually know posh-svn was on psget (I didn't contribute it to
there). I guess you'll need to send them a pull request to modify the
install location in their directory.xml. If they need me to authorise
anything then I'd be happy to do so.

**Comment by mbishopim3** [comment]
We've submitted the PsGet pull request, will close this once complete.

**Comment by mbishopim3** [comment]
They've merged it in and we'll take it from here. Thanks for a great extension! Not sure if you want to put up a README with a link to the new repo or not.

**Comment by JeremySkinner** [comment]
Thanks...that's done.
